### ISSUE TITLE
[Question] How to get rid of 'x' in search

### ISSUE THREAD

**Issue by lamalvin21** [komarovalexander/ka-table#365]
Hi,

I am currently using [this](https://komarovalexander.github.io/ka-table/#/search) search feature for my table and when typing a little blue 'x' (see image below) appears on the right to allow for the option to clear the search. Would it be possible to remove or restyle this? 

<img width="149" alt="Screenshot 2023-12-20 at 22 31 25" src="https://github.com/komarovalexander/ka-table/assets/91572346/18b46664-7ca8-4438-8abf-2a259f916075">

Thanks in advance!

**Comment by komarovalexander** [comment]
Hello @lamalvin21 it is separate component, and it is regular html input - You can remove it of course and you can even use another one input you want, but im not sure that this is correct place to solve this question, because as you can see this input is not part of the package and it is used outside of a table. Provided Searc demo just shows how you can setup searchValue to the table - and for this purpose you can use any components you want and customize them differently

**Comment by lamalvin21** [comment]
Solution to this problem:

https://davidwalsh.name/remove-clear-search

```
[type="search"]::-webkit-search-cancel-button,
[type="search"]::-webkit-search-decoration {
  -webkit-appearance: none;
  appearance: none;
}
```
