### ISSUE TITLE
Deselect range with shiftKey

### ISSUE THREAD

**Issue by boverU** [komarovalexander/ka-table#75]
Deselect from the range of selected items. For example, selected 100 items and I want to deselect from 20 to 40th element.

**Comment by komarovalexander** [comment]
Hello @boverU 
I created a demo https://stackblitz.com/edit/table-selection-ts-jvpr1r?file=Demo.tsx which you can use for implementing the solution for multiple deselect. 
In this demo I created a custom action `{ type: 'DeselectRange', rowKeyValue }` and pass it to `customReducer` - you can do it the same way
as for implementing it out-of-the-box - I did not found any cases in other grids how it can be implemented, I'm not sure that there is any good solution for multiple deselect because to implement it I have to save last deselected value - but looks like it is not a good option for tableProps

I will keep this issue opened, maybe more requests for this option will come
