### ISSUE TITLE
The scrollbar should not be a part of the header

### ISSUE THREAD

**Issue by yarokon** [komarovalexander/ka-table#82]
The scrollbar that takes the entire height of the table does not look very good compared to the scrollbar that only takes the height of the body. Is it possible to return the previous behavior as it was in all versions 4 and below?

![Selection_602](https://user-images.githubusercontent.com/4423716/91699738-6cfa3e00-eb7d-11ea-9601-8e4db02ece7b.png)

**Comment by komarovalexander** [comment]
Hello @yarokon. Thanks for the question. I'm on vacation and don't have my laptop with me. But I will be back in 4 days and will have a look at thus issue at the end of this week. Thanks again for being attentive to details and provide so valuable feedback

**Comment by komarovalexander** [comment]
Hi @yarokon  

ka-table with versions 4 and below had tbody with display: block

it worked ideally in case of overflow-y, but overflow-x had some issues because it did not scroll the header. 

To fix issues with overflow-x I had added some js hacks, they worked ok (actually mobile version had small delays) before I started the implementation of column reordering - I wanted to scroll the table when I move the element to the edge like this:
![image](https://user-images.githubusercontent.com/17903747/92244214-e918bc80-eec2-11ea-82e5-4b471f935ee8.png)
it works ideally if you have a native scroll implementation, but with the custom js-hack it required additional js to implement it.  I decided not to add a new hack and remove logic with display: block and add .ka-table-wrapper which natively supports scrolling stuff - this is the reason why you see scroll over the header.

I think it is good to avoid such types of hacks to make it easier to add new features, support, and decrease the size of the component. 

ka-table, it is a real HTML table in the markup and I like it because it behaves like a real table, and I don't think there is any solution to make only scrollable-y body and avoid js hacks for scrollable-x header in HTML table element.

if you want it to work as it was before you can add

```
.ka-table{
  display: block;
}
.ka-thead{
  overflow: hidden;
  display: block;
}
.ka-tr {
  display: table;
  width: 100%;
  table-layout: fixed;
}
.ka-tbody{
  display: block;
  max-height: 200px;
  overflow-y: auto;
}
```
https://stackblitz.com/edit/table-overview-ts-21wt5c?file=style.scss

but be aware that it has some side effects for header vertical scrolling in case of many columns

to fix issue with vertical scrolling I can propose this solution (starting from 5.1.0) version:

https://stackblitz.com/edit/table-overview-ts-hajo5t?file=Demo.tsx

**Comment by blinovksiyigor** [comment]
Hey @komarovalexander , i have the same issue with removing scrollbar in header. (6.4.3 ka-table version)
This what i have now [](https://stackblitz.com/edit/table-overview-ts-7ttw5y?file=Demo.tsx)
Is there a possibility to make this work without dispatching the scroll action (maybe some styles changes or additional props). I was using version 4.3.2 before and it worked just great.
Thanks

**Comment by komarovalexander** [comment]
Hi @blinovksiyigor 
thanks for feedback, at this time there is no option to implement it without additional code
I've just updated your example: 
https://stackblitz.com/edit/table-overview-ts-qwn9re?file=Demo.tsx

it works as before. In <= 4.*versions I've used the same approach but under the hood. Now it is not so good for performance and some new features
